<script src="{{url('')}}/assets/admin/app-assets/vendors/js/ui/popper.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/vendors.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/extensions/sweetalert.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/ui/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/ui/unison.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/ui/blockUI.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/ui/jquery-sliding-menu.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/extensions/toastr.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/ui/jquery.sticky.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/forms/icheck/icheck.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/forms/toggle/bootstrap-checkbox.min.js"  type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/forms/select/select2.full.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/forms/spinner/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/charts/jquery.sparkline.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/forms/toggle/bootstrap-switch.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/vendors/js/forms/toggle/switchery.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/js/scripts/forms/validation/form-validation.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/js/core/app-menu.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/js/core/app.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/js/scripts/customizer.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/js/scripts/pages/sk-content-sidebar.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/js/scripts/extensions/toastr.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/js/scripts/pages/sk-content-sidebar.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/js/scripts/forms/checkbox-radio.js" type="text/javascript"></script>
 <script src="{{url('')}}/assets/admin/app-assets/vendors/js/forms/tags/tagging.min.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/app-assets/js/scripts/forms/tags/tagging.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/filemanager/js/lfm.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/custom/custom.header.js" type="text/javascript"></script>
<script src="{{url('')}}/assets/admin/custom/custom.footer.js" type="text/javascript"></script>