@include('frontend.v1.general.header')
@include('frontend.v1.general.top-bar')
@include('frontend.v1.general.top')
@include('frontend.v1.general.header-menu')
@include('frontend.v1.general.top-menu')
@yield('content')
@include('frontend.v1.general.footer')
@include('frontend.v1.general.menu-mobile')